package timezonecompanion

var CCToZones = map[string][]string{
"VI": []string{"America/St_Thomas"},
"AW": []string{"America/Aruba"},
"GD": []string{"America/Grenada"},
"MV": []string{"Indian/Maldives"},
"RE": []string{"Indian/Reunion"},
"TH": []string{"Asia/Bangkok"},
"TJ": []string{"Asia/Dushanbe"},
"BQ": []string{"America/Kralendijk"},
"LK": []string{"Asia/Colombo"},
"SY": []string{"Asia/Damascus"},
"CL": []string{"America/Santiago", "America/Punta_Arenas", "Pacific/Easter"},
"DK": []string{"Europe/Copenhagen"},
"GI": []string{"Europe/Gibraltar"},
"TO": []string{"Pacific/Tongatapu"},
"UZ": []string{"Asia/Samarkand", "Asia/Tashkent"},
"CN": []string{"Asia/Shanghai", "Asia/Urumqi"},
"FJ": []string{"Pacific/Fiji"},
"ZW": []string{"Africa/Harare"},
"DO": []string{"America/Santo_Domingo"},
"UA": []string{"Europe/Kiev", "Europe/Uzhgorod", "Europe/Zaporozhye"},
"BW": []string{"Africa/Gaborone"},
"FO": []string{"Atlantic/Faroe"},
"ID": []string{"Asia/Jakarta", "Asia/Pontianak", "Asia/Makassar", "Asia/Jayapura"},
"ML": []string{"Africa/Bamako"},
"SG": []string{"Asia/Singapore"},
"AX": []string{"Europe/Mariehamn"},
"CZ": []string{"Europe/Prague"},
"IR": []string{"Asia/Tehran"},
"JE": []string{"Europe/Jersey"},
"KY": []string{"America/Cayman"},
"KZ": []string{"Asia/Almaty", "Asia/Qyzylorda", "Asia/Qostanay", "Asia/Aqtobe", "Asia/Aqtau", "Asia/Atyrau", "Asia/Oral"},
"MD": []string{"Europe/Chisinau"},
"PE": []string{"America/Lima"},
"VG": []string{"America/Tortola"},
"EE": []string{"Europe/Tallinn"},
"GM": []string{"Africa/Banjul"},
"IS": []string{"Atlantic/Reykjavik"},
"MC": []string{"Europe/Monaco"},
"BR": []string{"America/Noronha", "America/Belem", "America/Fortaleza", "America/Recife", "America/Araguaina", "America/Maceio", "America/Bahia", "America/Sao_Paulo", "America/Campo_Grande", "America/Cuiaba", "America/Santarem", "America/Porto_Velho", "America/Boa_Vista", "America/Manaus", "America/Eirunepe", "America/Rio_Branco"},
"QA": []string{"Asia/Qatar"},
"BY": []string{"Europe/Minsk"},
"IM": []string{"Europe/Isle_of_Man"},
"MA": []string{"Africa/Casablanca"},
"VU": []string{"Pacific/Efate"},
"CW": []string{"America/Curacao"},
"GQ": []string{"Africa/Malabo"},
"KI": []string{"Pacific/Tarawa", "Pacific/Enderbury", "Pacific/Kiritimati"},
"MM": []string{"Asia/Yangon"},
"PN": []string{"Pacific/Pitcairn"},
"ST": []string{"Africa/Sao_Tome"},
"HR": []string{"Europe/Zagreb"},
"KM": []string{"Indian/Comoro"},
"LB": []string{"Asia/Beirut"},
"PR": []string{"America/Puerto_Rico"},
"US": []string{"America/New_York", "America/Detroit", "America/Kentucky/Louisville", "America/Kentucky/Monticello", "America/Indiana/Indianapolis", "America/Indiana/Vincennes", "America/Indiana/Winamac", "America/Indiana/Marengo", "America/Indiana/Petersburg", "America/Indiana/Vevay", "America/Chicago", "America/Indiana/Tell_City", "America/Indiana/Knox", "America/Menominee", "America/North_Dakota/Center", "America/North_Dakota/New_Salem", "America/North_Dakota/Beulah", "America/Denver", "America/Boise", "America/Phoenix", "America/Los_Angeles", "America/Anchorage", "America/Juneau", "America/Sitka", "America/Metlakatla", "America/Yakutat", "America/Nome", "America/Adak", "Pacific/Honolulu"},
"YT": []string{"Indian/Mayotte"},
"BT": []string{"Asia/Thimphu"},
"EC": []string{"America/Guayaquil", "Pacific/Galapagos"},
"CD": []string{"Africa/Kinshasa", "Africa/Lubumbashi"},
"IN": []string{"Asia/Kolkata"},
"MX": []string{"America/Mexico_City", "America/Cancun", "America/Merida", "America/Monterrey", "America/Matamoros", "America/Mazatlan", "America/Chihuahua", "America/Ojinaga", "America/Hermosillo", "America/Tijuana", "America/Bahia_Banderas"},
"PL": []string{"Europe/Warsaw"},
"SI": []string{"Europe/Ljubljana"},
"SX": []string{"America/Lower_Princes"},
"AM": []string{"Asia/Yerevan"},
"HN": []string{"America/Tegucigalpa"},
"SH": []string{"Atlantic/St_Helena"},
"SK": []string{"Europe/Bratislava"},
"CV": []string{"Atlantic/Cape_Verde"},
"IE": []string{"Europe/Dublin"},
"SD": []string{"Africa/Khartoum"},
"TF": []string{"Indian/Kerguelen"},
"TL": []string{"Asia/Dili"},
"BJ": []string{"Africa/Porto-Novo"},
"DE": []string{"Europe/Berlin", "Europe/Busingen"},
"ES": []string{"Europe/Madrid", "Africa/Ceuta", "Atlantic/Canary"},
"GE": []string{"Asia/Tbilisi"},
"MH": []string{"Pacific/Majuro", "Pacific/Kwajalein"},
"NE": []string{"Africa/Niamey"},
"AT": []string{"Europe/Vienna"},
"LY": []string{"Africa/Tripoli"},
"ME": []string{"Europe/Podgorica"},
"ZA": []string{"Africa/Johannesburg"},
"CG": []string{"Africa/Brazzaville"},
"GY": []string{"America/Guyana"},
"LT": []string{"Europe/Vilnius"},
"PF": []string{"Pacific/Tahiti", "Pacific/Marquesas", "Pacific/Gambier"},
"CF": []string{"Africa/Bangui"},
"GL": []string{"America/Godthab", "America/Danmarkshavn", "America/Scoresbysund", "America/Thule"},
"CK": []string{"Pacific/Rarotonga"},
"GR": []string{"Europe/Athens"},
"RS": []string{"Europe/Belgrade"},
"BG": []string{"Europe/Sofia"},
"GN": []string{"Africa/Conakry"},
"NF": []string{"Pacific/Norfolk"},
"TR": []string{"Europe/Istanbul"},
"UG": []string{"Africa/Kampala"},
"CM": []string{"Africa/Douala"},
"CO": []string{"America/Bogota"},
"IQ": []string{"Asia/Baghdad"},
"WS": []string{"Pacific/Apia"},
"FM": []string{"Pacific/Chuuk", "Pacific/Pohnpei", "Pacific/Kosrae"},
"GH": []string{"Africa/Accra"},
"IT": []string{"Europe/Rome"},
"PY": []string{"America/Asuncion"},
"SM": []string{"Europe/San_Marino"},
"NU": []string{"Pacific/Niue"},
"SB": []string{"Pacific/Guadalcanal"},
"TN": []string{"Africa/Tunis"},
"UM": []string{"Pacific/Midway", "Pacific/Wake"},
"LC": []string{"America/St_Lucia"},
"LU": []string{"Europe/Luxembourg"},
"NA": []string{"Africa/Windhoek"},
"UY": []string{"America/Montevideo"},
"KW": []string{"Asia/Kuwait"},
"LI": []string{"Europe/Vaduz"},
"MQ": []string{"America/Martinique"},
"NL": []string{"Europe/Amsterdam"},
"GF": []string{"America/Cayenne"},
"NI": []string{"America/Managua"},
"PS": []string{"Asia/Gaza", "Asia/Hebron"},
"UK": []string{"Europe/London"},
"AR": []string{"America/Argentina/Buenos_Aires", "America/Argentina/Cordoba", "America/Argentina/Salta", "America/Argentina/Jujuy", "America/Argentina/Tucuman", "America/Argentina/Catamarca", "America/Argentina/La_Rioja", "America/Argentina/San_Juan", "America/Argentina/Mendoza", "America/Argentina/San_Luis", "America/Argentina/Rio_Gallegos", "America/Argentina/Ushuaia"},
"GS": []string{"Atlantic/South_Georgia"},
"GU": []string{"Pacific/Guam"},
"KG": []string{"Asia/Bishkek"},
"NR": []string{"Pacific/Nauru"},
"PT": []string{"Europe/Lisbon", "Atlantic/Madeira", "Atlantic/Azores"},
"AZ": []string{"Asia/Baku"},
"BF": []string{"Africa/Ouagadougou"},
"BI": []string{"Africa/Bujumbura"},
"BM": []string{"Atlantic/Bermuda"},
"CY": []string{"Asia/Nicosia", "Asia/Famagusta"},
"NC": []string{"Pacific/Noumea"},
"AS": []string{"Pacific/Pago_Pago"},
"ET": []string{"Africa/Addis_Ababa"},
"AI": []string{"America/Anguilla"},
"AU": []string{"Australia/Lord_Howe", "Antarctica/Macquarie", "Australia/Hobart", "Australia/Currie", "Australia/Melbourne", "Australia/Sydney", "Australia/Broken_Hill", "Australia/Brisbane", "Australia/Lindeman", "Australia/Adelaide", "Australia/Darwin", "Australia/Perth", "Australia/Eucla"},
"FR": []string{"Europe/Paris"},
"MT": []string{"Europe/Malta"},
"PG": []string{"Pacific/Port_Moresby", "Pacific/Bougainville"},
"BE": []string{"Europe/Brussels"},
"CC": []string{"Indian/Cocos"},
"MF": []string{"America/Marigot"},
"BN": []string{"Asia/Brunei"},
"ER": []string{"Africa/Asmara"},
"GW": []string{"Africa/Bissau"},
"RO": []string{"Europe/Bucharest"},
"VE": []string{"America/Caracas"},
"JP": []string{"Asia/Tokyo"},
"NP": []string{"Asia/Kathmandu"},
"VC": []string{"America/St_Vincent"},
"VN": []string{"Asia/Ho_Chi_Minh"},
"BB": []string{"America/Barbados"},
"KP": []string{"Asia/Pyongyang"},
"SO": []string{"Africa/Mogadishu"},
"SV": []string{"America/El_Salvador"},
"TW": []string{"Asia/Taipei"},
"IO": []string{"Indian/Chagos"},
"OM": []string{"Asia/Muscat"},
"TD": []string{"Africa/Ndjamena"},
"MN": []string{"Asia/Ulaanbaatar", "Asia/Hovd", "Asia/Choibalsan"},
"SC": []string{"Indian/Mahe"},
"CU": []string{"America/Havana"},
"SS": []string{"Africa/Juba"},
"TK": []string{"Pacific/Fakaofo"},
"ZM": []string{"Africa/Lusaka"},
"BD": []string{"Asia/Dhaka"},
"NO": []string{"Europe/Oslo"},
"SA": []string{"Asia/Riyadh"},
"AF": []string{"Asia/Kabul"},
"CA": []string{"America/St_Johns", "America/Halifax", "America/Glace_Bay", "America/Moncton", "America/Goose_Bay", "America/Blanc-Sablon", "America/Toronto", "America/Nipigon", "America/Thunder_Bay", "America/Iqaluit", "America/Pangnirtung", "America/Atikokan", "America/Winnipeg", "America/Rainy_River", "America/Resolute", "America/Rankin_Inlet", "America/Regina", "America/Swift_Current", "America/Edmonton", "America/Cambridge_Bay", "America/Yellowknife", "America/Inuvik", "America/Creston", "America/Dawson_Creek", "America/Fort_Nelson", "America/Vancouver", "America/Whitehorse", "America/Dawson"},
"CR": []string{"America/Costa_Rica"},
"GT": []string{"America/Guatemala"},
"JM": []string{"America/Jamaica"},
"LV": []string{"Europe/Riga"},
"BA": []string{"Europe/Sarajevo"},
"GG": []string{"Europe/Guernsey"},
"AO": []string{"Africa/Luanda"},
"BS": []string{"America/Nassau"},
"PW": []string{"Pacific/Palau"},
"RU": []string{"Europe/Kaliningrad", "Europe/Moscow", "Europe/Simferopol", "Europe/Kirov", "Europe/Astrakhan", "Europe/Volgograd", "Europe/Saratov", "Europe/Ulyanovsk", "Europe/Samara", "Asia/Yekaterinburg", "Asia/Omsk", "Asia/Novosibirsk", "Asia/Barnaul", "Asia/Tomsk", "Asia/Novokuznetsk", "Asia/Krasnoyarsk", "Asia/Irkutsk", "Asia/Chita", "Asia/Yakutsk", "Asia/Khandyga", "Asia/Vladivostok", "Asia/Ust-Nera", "Asia/Magadan", "Asia/Sakhalin", "Asia/Srednekolymsk", "Asia/Kamchatka", "Asia/Anadyr"},
"RW": []string{"Africa/Kigali"},
"SE": []string{"Europe/Stockholm"},
"AG": []string{"America/Antigua"},
"EH": []string{"Africa/El_Aaiun"},
"HT": []string{"America/Port-au-Prince"},
"JO": []string{"Asia/Amman"},
"LA": []string{"Asia/Vientiane"},
"NZ": []string{"Pacific/Auckland", "Pacific/Chatham"},
"VA": []string{"Europe/Vatican"},
"BZ": []string{"America/Belize"},
"FI": []string{"Europe/Helsinki"},
"PM": []string{"America/Miquelon"},
"TC": []string{"America/Grand_Turk"},
"BL": []string{"America/St_Barthelemy"},
"SZ": []string{"Africa/Mbabane"},
"MG": []string{"Indian/Antananarivo"},
"MR": []string{"Africa/Nouakchott"},
"MW": []string{"Africa/Blantyre"},
"HU": []string{"Europe/Budapest"},
"MS": []string{"America/Montserrat"},
"CH": []string{"Europe/Zurich"},
"CI": []string{"Africa/Abidjan"},
"MZ": []string{"Africa/Maputo"},
"AL": []string{"Europe/Tirane"},
"BO": []string{"America/La_Paz"},
"FK": []string{"Atlantic/Stanley"},
"KH": []string{"Asia/Phnom_Penh"},
"PK": []string{"Asia/Karachi"},
"SJ": []string{"Arctic/Longyearbyen"},
"SL": []string{"Africa/Freetown"},
"DJ": []string{"Africa/Djibouti"},
"MU": []string{"Indian/Mauritius"},
"TT": []string{"America/Port_of_Spain"},
"DM": []string{"America/Dominica"},
"HK": []string{"Asia/Hong_Kong"},
"KN": []string{"America/St_Kitts"},
"MK": []string{"Europe/Skopje"},
"MP": []string{"Pacific/Saipan"},
"NG": []string{"Africa/Lagos"},
"CX": []string{"Indian/Christmas"},
"SN": []string{"Africa/Dakar"},
"AD": []string{"Europe/Andorra"},
"DZ": []string{"Africa/Algiers"},
"PH": []string{"Asia/Manila"},
"SR": []string{"America/Paramaribo"},
"TM": []string{"Asia/Ashgabat"},
"AQ": []string{"Antarctica/McMurdo", "Antarctica/Casey", "Antarctica/Davis", "Antarctica/DumontDUrville", "Antarctica/Mawson", "Antarctica/Palmer", "Antarctica/Rothera", "Antarctica/Syowa", "Antarctica/Troll", "Antarctica/Vostok"},
"BH": []string{"Asia/Bahrain"},
"LS": []string{"Africa/Maseru"},
"TZ": []string{"Africa/Dar_es_Salaam"},
"EG": []string{"Africa/Cairo"},
"KR": []string{"Asia/Seoul"},
"TG": []string{"Africa/Lome"},
"WF": []string{"Pacific/Wallis"},
"GA": []string{"Africa/Libreville"},
"IL": []string{"Asia/Jerusalem"},
"KE": []string{"Africa/Nairobi"},
"LR": []string{"Africa/Monrovia"},
"MY": []string{"Asia/Kuala_Lumpur", "Asia/Kuching"},
"PA": []string{"America/Panama"},
"AE": []string{"Asia/Dubai"},
"GB": []string{"Europe/London"},
"GP": []string{"America/Guadeloupe"},
"MO": []string{"Asia/Macau"},
"TV": []string{"Pacific/Funafuti"},
"YE": []string{"Asia/Aden"},
}