// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	EconomyConfigs       string
	EconomyLogs          string
	EconomyPickImages2   string
	EconomyPlants        string
	EconomyShopItems     string
	EconomyShopListItems string
	EconomyUsers         string
	EconomyWaifuItems    string
}{
	EconomyConfigs:       "economy_configs",
	EconomyLogs:          "economy_logs",
	EconomyPickImages2:   "economy_pick_images2",
	EconomyPlants:        "economy_plants",
	EconomyShopItems:     "economy_shop_items",
	EconomyShopListItems: "economy_shop_list_items",
	EconomyUsers:         "economy_users",
	EconomyWaifuItems:    "economy_waifu_items",
}
