// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// EconomyShopItem is an object representing the database table.
type EconomyShopItem struct {
	GuildID                 int64  `boil:"guild_id" json:"guild_id" toml:"guild_id" yaml:"guild_id"`
	LocalID                 int64  `boil:"local_id" json:"local_id" toml:"local_id" yaml:"local_id"`
	Icon                    string `boil:"icon" json:"icon" toml:"icon" yaml:"icon"`
	Name                    string `boil:"name" json:"name" toml:"name" yaml:"name"`
	RoleID                  int64  `boil:"role_id" json:"role_id" toml:"role_id" yaml:"role_id"`
	GamblingBoostPercentage int    `boil:"gambling_boost_percentage" json:"gambling_boost_percentage" toml:"gambling_boost_percentage" yaml:"gambling_boost_percentage"`
	Cost                    int64  `boil:"cost" json:"cost" toml:"cost" yaml:"cost"`
	Type                    int16  `boil:"type" json:"type" toml:"type" yaml:"type"`

	R *economyShopItemR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L economyShopItemL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var EconomyShopItemColumns = struct {
	GuildID                 string
	LocalID                 string
	Icon                    string
	Name                    string
	RoleID                  string
	GamblingBoostPercentage string
	Cost                    string
	Type                    string
}{
	GuildID:                 "guild_id",
	LocalID:                 "local_id",
	Icon:                    "icon",
	Name:                    "name",
	RoleID:                  "role_id",
	GamblingBoostPercentage: "gambling_boost_percentage",
	Cost:                    "cost",
	Type:                    "type",
}

var EconomyShopItemTableColumns = struct {
	GuildID                 string
	LocalID                 string
	Icon                    string
	Name                    string
	RoleID                  string
	GamblingBoostPercentage string
	Cost                    string
	Type                    string
}{
	GuildID:                 "economy_shop_items.guild_id",
	LocalID:                 "economy_shop_items.local_id",
	Icon:                    "economy_shop_items.icon",
	Name:                    "economy_shop_items.name",
	RoleID:                  "economy_shop_items.role_id",
	GamblingBoostPercentage: "economy_shop_items.gambling_boost_percentage",
	Cost:                    "economy_shop_items.cost",
	Type:                    "economy_shop_items.type",
}

// Generated where

var EconomyShopItemWhere = struct {
	GuildID                 whereHelperint64
	LocalID                 whereHelperint64
	Icon                    whereHelperstring
	Name                    whereHelperstring
	RoleID                  whereHelperint64
	GamblingBoostPercentage whereHelperint
	Cost                    whereHelperint64
	Type                    whereHelperint16
}{
	GuildID:                 whereHelperint64{field: "\"economy_shop_items\".\"guild_id\""},
	LocalID:                 whereHelperint64{field: "\"economy_shop_items\".\"local_id\""},
	Icon:                    whereHelperstring{field: "\"economy_shop_items\".\"icon\""},
	Name:                    whereHelperstring{field: "\"economy_shop_items\".\"name\""},
	RoleID:                  whereHelperint64{field: "\"economy_shop_items\".\"role_id\""},
	GamblingBoostPercentage: whereHelperint{field: "\"economy_shop_items\".\"gambling_boost_percentage\""},
	Cost:                    whereHelperint64{field: "\"economy_shop_items\".\"cost\""},
	Type:                    whereHelperint16{field: "\"economy_shop_items\".\"type\""},
}

// EconomyShopItemRels is where relationship names are stored.
var EconomyShopItemRels = struct {
}{}

// economyShopItemR is where relationships are stored.
type economyShopItemR struct {
}

// NewStruct creates a new relationship struct
func (*economyShopItemR) NewStruct() *economyShopItemR {
	return &economyShopItemR{}
}

// economyShopItemL is where Load methods for each relationship are stored.
type economyShopItemL struct{}

var (
	economyShopItemAllColumns            = []string{"guild_id", "local_id", "icon", "name", "role_id", "gambling_boost_percentage", "cost", "type"}
	economyShopItemColumnsWithoutDefault = []string{"guild_id", "local_id", "icon", "name", "role_id", "gambling_boost_percentage", "cost", "type"}
	economyShopItemColumnsWithDefault    = []string{}
	economyShopItemPrimaryKeyColumns     = []string{"guild_id", "local_id"}
	economyShopItemGeneratedColumns      = []string{}
)

type (
	// EconomyShopItemSlice is an alias for a slice of pointers to EconomyShopItem.
	// This should almost always be used instead of []EconomyShopItem.
	EconomyShopItemSlice []*EconomyShopItem

	economyShopItemQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	economyShopItemType                 = reflect.TypeOf(&EconomyShopItem{})
	economyShopItemMapping              = queries.MakeStructMapping(economyShopItemType)
	economyShopItemPrimaryKeyMapping, _ = queries.BindMapping(economyShopItemType, economyShopItemMapping, economyShopItemPrimaryKeyColumns)
	economyShopItemInsertCacheMut       sync.RWMutex
	economyShopItemInsertCache          = make(map[string]insertCache)
	economyShopItemUpdateCacheMut       sync.RWMutex
	economyShopItemUpdateCache          = make(map[string]updateCache)
	economyShopItemUpsertCacheMut       sync.RWMutex
	economyShopItemUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// OneG returns a single economyShopItem record from the query using the global executor.
func (q economyShopItemQuery) OneG(ctx context.Context) (*EconomyShopItem, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single economyShopItem record from the query.
func (q economyShopItemQuery) One(ctx context.Context, exec boil.ContextExecutor) (*EconomyShopItem, error) {
	o := &EconomyShopItem{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for economy_shop_items")
	}

	return o, nil
}

// AllG returns all EconomyShopItem records from the query using the global executor.
func (q economyShopItemQuery) AllG(ctx context.Context) (EconomyShopItemSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all EconomyShopItem records from the query.
func (q economyShopItemQuery) All(ctx context.Context, exec boil.ContextExecutor) (EconomyShopItemSlice, error) {
	var o []*EconomyShopItem

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to EconomyShopItem slice")
	}

	return o, nil
}

// CountG returns the count of all EconomyShopItem records in the query using the global executor
func (q economyShopItemQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all EconomyShopItem records in the query.
func (q economyShopItemQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count economy_shop_items rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q economyShopItemQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q economyShopItemQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if economy_shop_items exists")
	}

	return count > 0, nil
}

// EconomyShopItems retrieves all the records using an executor.
func EconomyShopItems(mods ...qm.QueryMod) economyShopItemQuery {
	mods = append(mods, qm.From("\"economy_shop_items\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"economy_shop_items\".*"})
	}

	return economyShopItemQuery{q}
}

// FindEconomyShopItemG retrieves a single record by ID.
func FindEconomyShopItemG(ctx context.Context, guildID int64, localID int64, selectCols ...string) (*EconomyShopItem, error) {
	return FindEconomyShopItem(ctx, boil.GetContextDB(), guildID, localID, selectCols...)
}

// FindEconomyShopItem retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindEconomyShopItem(ctx context.Context, exec boil.ContextExecutor, guildID int64, localID int64, selectCols ...string) (*EconomyShopItem, error) {
	economyShopItemObj := &EconomyShopItem{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"economy_shop_items\" where \"guild_id\"=$1 AND \"local_id\"=$2", sel,
	)

	q := queries.Raw(query, guildID, localID)

	err := q.Bind(ctx, exec, economyShopItemObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from economy_shop_items")
	}

	return economyShopItemObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *EconomyShopItem) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *EconomyShopItem) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no economy_shop_items provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(economyShopItemColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	economyShopItemInsertCacheMut.RLock()
	cache, cached := economyShopItemInsertCache[key]
	economyShopItemInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			economyShopItemAllColumns,
			economyShopItemColumnsWithDefault,
			economyShopItemColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(economyShopItemType, economyShopItemMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(economyShopItemType, economyShopItemMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"economy_shop_items\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"economy_shop_items\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into economy_shop_items")
	}

	if !cached {
		economyShopItemInsertCacheMut.Lock()
		economyShopItemInsertCache[key] = cache
		economyShopItemInsertCacheMut.Unlock()
	}

	return nil
}

// UpdateG a single EconomyShopItem record using the global executor.
// See Update for more documentation.
func (o *EconomyShopItem) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the EconomyShopItem.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *EconomyShopItem) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	economyShopItemUpdateCacheMut.RLock()
	cache, cached := economyShopItemUpdateCache[key]
	economyShopItemUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			economyShopItemAllColumns,
			economyShopItemPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update economy_shop_items, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"economy_shop_items\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, economyShopItemPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(economyShopItemType, economyShopItemMapping, append(wl, economyShopItemPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update economy_shop_items row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for economy_shop_items")
	}

	if !cached {
		economyShopItemUpdateCacheMut.Lock()
		economyShopItemUpdateCache[key] = cache
		economyShopItemUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (q economyShopItemQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q economyShopItemQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for economy_shop_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for economy_shop_items")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o EconomyShopItemSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o EconomyShopItemSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), economyShopItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"economy_shop_items\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, economyShopItemPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in economyShopItem slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all economyShopItem")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *EconomyShopItem) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *EconomyShopItem) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no economy_shop_items provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(economyShopItemColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	economyShopItemUpsertCacheMut.RLock()
	cache, cached := economyShopItemUpsertCache[key]
	economyShopItemUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			economyShopItemAllColumns,
			economyShopItemColumnsWithDefault,
			economyShopItemColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			economyShopItemAllColumns,
			economyShopItemPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert economy_shop_items, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(economyShopItemPrimaryKeyColumns))
			copy(conflict, economyShopItemPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"economy_shop_items\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(economyShopItemType, economyShopItemMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(economyShopItemType, economyShopItemMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert economy_shop_items")
	}

	if !cached {
		economyShopItemUpsertCacheMut.Lock()
		economyShopItemUpsertCache[key] = cache
		economyShopItemUpsertCacheMut.Unlock()
	}

	return nil
}

// DeleteG deletes a single EconomyShopItem record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *EconomyShopItem) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single EconomyShopItem record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *EconomyShopItem) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no EconomyShopItem provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), economyShopItemPrimaryKeyMapping)
	sql := "DELETE FROM \"economy_shop_items\" WHERE \"guild_id\"=$1 AND \"local_id\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from economy_shop_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for economy_shop_items")
	}

	return rowsAff, nil
}

func (q economyShopItemQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q economyShopItemQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no economyShopItemQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from economy_shop_items")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for economy_shop_items")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o EconomyShopItemSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o EconomyShopItemSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), economyShopItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"economy_shop_items\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, economyShopItemPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from economyShopItem slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for economy_shop_items")
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *EconomyShopItem) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no EconomyShopItem provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *EconomyShopItem) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindEconomyShopItem(ctx, exec, o.GuildID, o.LocalID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EconomyShopItemSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty EconomyShopItemSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EconomyShopItemSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := EconomyShopItemSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), economyShopItemPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"economy_shop_items\".* FROM \"economy_shop_items\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, economyShopItemPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in EconomyShopItemSlice")
	}

	*o = slice

	return nil
}

// EconomyShopItemExistsG checks if the EconomyShopItem row exists.
func EconomyShopItemExistsG(ctx context.Context, guildID int64, localID int64) (bool, error) {
	return EconomyShopItemExists(ctx, boil.GetContextDB(), guildID, localID)
}

// EconomyShopItemExists checks if the EconomyShopItem row exists.
func EconomyShopItemExists(ctx context.Context, exec boil.ContextExecutor, guildID int64, localID int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"economy_shop_items\" where \"guild_id\"=$1 AND \"local_id\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, guildID, localID)
	}
	row := exec.QueryRowContext(ctx, sql, guildID, localID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if economy_shop_items exists")
	}

	return exists, nil
}
