// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// EconomyPickImages2 is an object representing the database table.
type EconomyPickImages2 struct {
	ID      int64  `boil:"id" json:"id" toml:"id" yaml:"id"`
	GuildID int64  `boil:"guild_id" json:"guild_id" toml:"guild_id" yaml:"guild_id"`
	Image   []byte `boil:"image" json:"image" toml:"image" yaml:"image"`

	R *economyPickImages2R `boil:"-" json:"-" toml:"-" yaml:"-"`
	L economyPickImages2L  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var EconomyPickImages2Columns = struct {
	ID      string
	GuildID string
	Image   string
}{
	ID:      "id",
	GuildID: "guild_id",
	Image:   "image",
}

var EconomyPickImages2TableColumns = struct {
	ID      string
	GuildID string
	Image   string
}{
	ID:      "economy_pick_images2.id",
	GuildID: "economy_pick_images2.guild_id",
	Image:   "economy_pick_images2.image",
}

// Generated where

type whereHelper__byte struct{ field string }

func (w whereHelper__byte) EQ(x []byte) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelper__byte) NEQ(x []byte) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelper__byte) LT(x []byte) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelper__byte) LTE(x []byte) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelper__byte) GT(x []byte) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelper__byte) GTE(x []byte) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }

var EconomyPickImages2Where = struct {
	ID      whereHelperint64
	GuildID whereHelperint64
	Image   whereHelper__byte
}{
	ID:      whereHelperint64{field: "\"economy_pick_images2\".\"id\""},
	GuildID: whereHelperint64{field: "\"economy_pick_images2\".\"guild_id\""},
	Image:   whereHelper__byte{field: "\"economy_pick_images2\".\"image\""},
}

// EconomyPickImages2Rels is where relationship names are stored.
var EconomyPickImages2Rels = struct {
}{}

// economyPickImages2R is where relationships are stored.
type economyPickImages2R struct {
}

// NewStruct creates a new relationship struct
func (*economyPickImages2R) NewStruct() *economyPickImages2R {
	return &economyPickImages2R{}
}

// economyPickImages2L is where Load methods for each relationship are stored.
type economyPickImages2L struct{}

var (
	economyPickImages2AllColumns            = []string{"id", "guild_id", "image"}
	economyPickImages2ColumnsWithoutDefault = []string{"guild_id", "image"}
	economyPickImages2ColumnsWithDefault    = []string{"id"}
	economyPickImages2PrimaryKeyColumns     = []string{"id"}
	economyPickImages2GeneratedColumns      = []string{}
)

type (
	// EconomyPickImages2Slice is an alias for a slice of pointers to EconomyPickImages2.
	// This should almost always be used instead of []EconomyPickImages2.
	EconomyPickImages2Slice []*EconomyPickImages2

	economyPickImages2Query struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	economyPickImages2Type                 = reflect.TypeOf(&EconomyPickImages2{})
	economyPickImages2Mapping              = queries.MakeStructMapping(economyPickImages2Type)
	economyPickImages2PrimaryKeyMapping, _ = queries.BindMapping(economyPickImages2Type, economyPickImages2Mapping, economyPickImages2PrimaryKeyColumns)
	economyPickImages2InsertCacheMut       sync.RWMutex
	economyPickImages2InsertCache          = make(map[string]insertCache)
	economyPickImages2UpdateCacheMut       sync.RWMutex
	economyPickImages2UpdateCache          = make(map[string]updateCache)
	economyPickImages2UpsertCacheMut       sync.RWMutex
	economyPickImages2UpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// OneG returns a single economyPickImages2 record from the query using the global executor.
func (q economyPickImages2Query) OneG(ctx context.Context) (*EconomyPickImages2, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single economyPickImages2 record from the query.
func (q economyPickImages2Query) One(ctx context.Context, exec boil.ContextExecutor) (*EconomyPickImages2, error) {
	o := &EconomyPickImages2{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for economy_pick_images2")
	}

	return o, nil
}

// AllG returns all EconomyPickImages2 records from the query using the global executor.
func (q economyPickImages2Query) AllG(ctx context.Context) (EconomyPickImages2Slice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all EconomyPickImages2 records from the query.
func (q economyPickImages2Query) All(ctx context.Context, exec boil.ContextExecutor) (EconomyPickImages2Slice, error) {
	var o []*EconomyPickImages2

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to EconomyPickImages2 slice")
	}

	return o, nil
}

// CountG returns the count of all EconomyPickImages2 records in the query using the global executor
func (q economyPickImages2Query) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all EconomyPickImages2 records in the query.
func (q economyPickImages2Query) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count economy_pick_images2 rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q economyPickImages2Query) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q economyPickImages2Query) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if economy_pick_images2 exists")
	}

	return count > 0, nil
}

// EconomyPickImages2s retrieves all the records using an executor.
func EconomyPickImages2s(mods ...qm.QueryMod) economyPickImages2Query {
	mods = append(mods, qm.From("\"economy_pick_images2\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"economy_pick_images2\".*"})
	}

	return economyPickImages2Query{q}
}

// FindEconomyPickImages2G retrieves a single record by ID.
func FindEconomyPickImages2G(ctx context.Context, iD int64, selectCols ...string) (*EconomyPickImages2, error) {
	return FindEconomyPickImages2(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindEconomyPickImages2 retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindEconomyPickImages2(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*EconomyPickImages2, error) {
	economyPickImages2Obj := &EconomyPickImages2{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"economy_pick_images2\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, economyPickImages2Obj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from economy_pick_images2")
	}

	return economyPickImages2Obj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *EconomyPickImages2) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *EconomyPickImages2) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no economy_pick_images2 provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(economyPickImages2ColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	economyPickImages2InsertCacheMut.RLock()
	cache, cached := economyPickImages2InsertCache[key]
	economyPickImages2InsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			economyPickImages2AllColumns,
			economyPickImages2ColumnsWithDefault,
			economyPickImages2ColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(economyPickImages2Type, economyPickImages2Mapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(economyPickImages2Type, economyPickImages2Mapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"economy_pick_images2\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"economy_pick_images2\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into economy_pick_images2")
	}

	if !cached {
		economyPickImages2InsertCacheMut.Lock()
		economyPickImages2InsertCache[key] = cache
		economyPickImages2InsertCacheMut.Unlock()
	}

	return nil
}

// UpdateG a single EconomyPickImages2 record using the global executor.
// See Update for more documentation.
func (o *EconomyPickImages2) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the EconomyPickImages2.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *EconomyPickImages2) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	economyPickImages2UpdateCacheMut.RLock()
	cache, cached := economyPickImages2UpdateCache[key]
	economyPickImages2UpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			economyPickImages2AllColumns,
			economyPickImages2PrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update economy_pick_images2, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"economy_pick_images2\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, economyPickImages2PrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(economyPickImages2Type, economyPickImages2Mapping, append(wl, economyPickImages2PrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update economy_pick_images2 row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for economy_pick_images2")
	}

	if !cached {
		economyPickImages2UpdateCacheMut.Lock()
		economyPickImages2UpdateCache[key] = cache
		economyPickImages2UpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (q economyPickImages2Query) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q economyPickImages2Query) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for economy_pick_images2")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for economy_pick_images2")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o EconomyPickImages2Slice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o EconomyPickImages2Slice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), economyPickImages2PrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"economy_pick_images2\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, economyPickImages2PrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in economyPickImages2 slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all economyPickImages2")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *EconomyPickImages2) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *EconomyPickImages2) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no economy_pick_images2 provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(economyPickImages2ColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	economyPickImages2UpsertCacheMut.RLock()
	cache, cached := economyPickImages2UpsertCache[key]
	economyPickImages2UpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			economyPickImages2AllColumns,
			economyPickImages2ColumnsWithDefault,
			economyPickImages2ColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			economyPickImages2AllColumns,
			economyPickImages2PrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert economy_pick_images2, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(economyPickImages2PrimaryKeyColumns))
			copy(conflict, economyPickImages2PrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"economy_pick_images2\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(economyPickImages2Type, economyPickImages2Mapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(economyPickImages2Type, economyPickImages2Mapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert economy_pick_images2")
	}

	if !cached {
		economyPickImages2UpsertCacheMut.Lock()
		economyPickImages2UpsertCache[key] = cache
		economyPickImages2UpsertCacheMut.Unlock()
	}

	return nil
}

// DeleteG deletes a single EconomyPickImages2 record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *EconomyPickImages2) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single EconomyPickImages2 record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *EconomyPickImages2) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no EconomyPickImages2 provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), economyPickImages2PrimaryKeyMapping)
	sql := "DELETE FROM \"economy_pick_images2\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from economy_pick_images2")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for economy_pick_images2")
	}

	return rowsAff, nil
}

func (q economyPickImages2Query) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q economyPickImages2Query) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no economyPickImages2Query provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from economy_pick_images2")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for economy_pick_images2")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o EconomyPickImages2Slice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o EconomyPickImages2Slice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), economyPickImages2PrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"economy_pick_images2\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, economyPickImages2PrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from economyPickImages2 slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for economy_pick_images2")
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *EconomyPickImages2) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no EconomyPickImages2 provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *EconomyPickImages2) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindEconomyPickImages2(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EconomyPickImages2Slice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty EconomyPickImages2Slice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EconomyPickImages2Slice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := EconomyPickImages2Slice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), economyPickImages2PrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"economy_pick_images2\".* FROM \"economy_pick_images2\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, economyPickImages2PrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in EconomyPickImages2Slice")
	}

	*o = slice

	return nil
}

// EconomyPickImages2ExistsG checks if the EconomyPickImages2 row exists.
func EconomyPickImages2ExistsG(ctx context.Context, iD int64) (bool, error) {
	return EconomyPickImages2Exists(ctx, boil.GetContextDB(), iD)
}

// EconomyPickImages2Exists checks if the EconomyPickImages2 row exists.
func EconomyPickImages2Exists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"economy_pick_images2\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if economy_pick_images2 exists")
	}

	return exists, nil
}
