// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// RSSAnnouncement is an object representing the database table.
type RSSAnnouncement struct {
	GuildID      int64  `boil:"guild_id" json:"guild_id" toml:"guild_id" yaml:"guild_id"`
	Announcement string `boil:"announcement" json:"announcement" toml:"announcement" yaml:"announcement"`
	Enabled      bool   `boil:"enabled" json:"enabled" toml:"enabled" yaml:"enabled"`

	R *rssAnnouncementR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L rssAnnouncementL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var RSSAnnouncementColumns = struct {
	GuildID      string
	Announcement string
	Enabled      string
}{
	GuildID:      "guild_id",
	Announcement: "announcement",
	Enabled:      "enabled",
}

var RSSAnnouncementTableColumns = struct {
	GuildID      string
	Announcement string
	Enabled      string
}{
	GuildID:      "rss_announcements.guild_id",
	Announcement: "rss_announcements.announcement",
	Enabled:      "rss_announcements.enabled",
}

// Generated where

type whereHelperint64 struct{ field string }

func (w whereHelperint64) EQ(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint64) NEQ(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint64) LT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint64) LTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint64) GT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint64) GTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint64) IN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint64) NIN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperbool struct{ field string }

func (w whereHelperbool) EQ(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperbool) NEQ(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperbool) LT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperbool) LTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperbool) GT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperbool) GTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }

var RSSAnnouncementWhere = struct {
	GuildID      whereHelperint64
	Announcement whereHelperstring
	Enabled      whereHelperbool
}{
	GuildID:      whereHelperint64{field: "\"rss_announcements\".\"guild_id\""},
	Announcement: whereHelperstring{field: "\"rss_announcements\".\"announcement\""},
	Enabled:      whereHelperbool{field: "\"rss_announcements\".\"enabled\""},
}

// RSSAnnouncementRels is where relationship names are stored.
var RSSAnnouncementRels = struct {
}{}

// rssAnnouncementR is where relationships are stored.
type rssAnnouncementR struct {
}

// NewStruct creates a new relationship struct
func (*rssAnnouncementR) NewStruct() *rssAnnouncementR {
	return &rssAnnouncementR{}
}

// rssAnnouncementL is where Load methods for each relationship are stored.
type rssAnnouncementL struct{}

var (
	rssAnnouncementAllColumns            = []string{"guild_id", "announcement", "enabled"}
	rssAnnouncementColumnsWithoutDefault = []string{"guild_id", "announcement"}
	rssAnnouncementColumnsWithDefault    = []string{"enabled"}
	rssAnnouncementPrimaryKeyColumns     = []string{"guild_id"}
	rssAnnouncementGeneratedColumns      = []string{}
)

type (
	// RSSAnnouncementSlice is an alias for a slice of pointers to RSSAnnouncement.
	// This should almost always be used instead of []RSSAnnouncement.
	RSSAnnouncementSlice []*RSSAnnouncement

	rssAnnouncementQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	rssAnnouncementType                 = reflect.TypeOf(&RSSAnnouncement{})
	rssAnnouncementMapping              = queries.MakeStructMapping(rssAnnouncementType)
	rssAnnouncementPrimaryKeyMapping, _ = queries.BindMapping(rssAnnouncementType, rssAnnouncementMapping, rssAnnouncementPrimaryKeyColumns)
	rssAnnouncementInsertCacheMut       sync.RWMutex
	rssAnnouncementInsertCache          = make(map[string]insertCache)
	rssAnnouncementUpdateCacheMut       sync.RWMutex
	rssAnnouncementUpdateCache          = make(map[string]updateCache)
	rssAnnouncementUpsertCacheMut       sync.RWMutex
	rssAnnouncementUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// OneG returns a single rssAnnouncement record from the query using the global executor.
func (q rssAnnouncementQuery) OneG(ctx context.Context) (*RSSAnnouncement, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single rssAnnouncement record from the query.
func (q rssAnnouncementQuery) One(ctx context.Context, exec boil.ContextExecutor) (*RSSAnnouncement, error) {
	o := &RSSAnnouncement{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for rss_announcements")
	}

	return o, nil
}

// AllG returns all RSSAnnouncement records from the query using the global executor.
func (q rssAnnouncementQuery) AllG(ctx context.Context) (RSSAnnouncementSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all RSSAnnouncement records from the query.
func (q rssAnnouncementQuery) All(ctx context.Context, exec boil.ContextExecutor) (RSSAnnouncementSlice, error) {
	var o []*RSSAnnouncement

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to RSSAnnouncement slice")
	}

	return o, nil
}

// CountG returns the count of all RSSAnnouncement records in the query using the global executor
func (q rssAnnouncementQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all RSSAnnouncement records in the query.
func (q rssAnnouncementQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count rss_announcements rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q rssAnnouncementQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q rssAnnouncementQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if rss_announcements exists")
	}

	return count > 0, nil
}

// RSSAnnouncements retrieves all the records using an executor.
func RSSAnnouncements(mods ...qm.QueryMod) rssAnnouncementQuery {
	mods = append(mods, qm.From("\"rss_announcements\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"rss_announcements\".*"})
	}

	return rssAnnouncementQuery{q}
}

// FindRSSAnnouncementG retrieves a single record by ID.
func FindRSSAnnouncementG(ctx context.Context, guildID int64, selectCols ...string) (*RSSAnnouncement, error) {
	return FindRSSAnnouncement(ctx, boil.GetContextDB(), guildID, selectCols...)
}

// FindRSSAnnouncement retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindRSSAnnouncement(ctx context.Context, exec boil.ContextExecutor, guildID int64, selectCols ...string) (*RSSAnnouncement, error) {
	rssAnnouncementObj := &RSSAnnouncement{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"rss_announcements\" where \"guild_id\"=$1", sel,
	)

	q := queries.Raw(query, guildID)

	err := q.Bind(ctx, exec, rssAnnouncementObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from rss_announcements")
	}

	return rssAnnouncementObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *RSSAnnouncement) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *RSSAnnouncement) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no rss_announcements provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(rssAnnouncementColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	rssAnnouncementInsertCacheMut.RLock()
	cache, cached := rssAnnouncementInsertCache[key]
	rssAnnouncementInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			rssAnnouncementAllColumns,
			rssAnnouncementColumnsWithDefault,
			rssAnnouncementColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(rssAnnouncementType, rssAnnouncementMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(rssAnnouncementType, rssAnnouncementMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"rss_announcements\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"rss_announcements\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into rss_announcements")
	}

	if !cached {
		rssAnnouncementInsertCacheMut.Lock()
		rssAnnouncementInsertCache[key] = cache
		rssAnnouncementInsertCacheMut.Unlock()
	}

	return nil
}

// UpdateG a single RSSAnnouncement record using the global executor.
// See Update for more documentation.
func (o *RSSAnnouncement) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the RSSAnnouncement.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *RSSAnnouncement) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	rssAnnouncementUpdateCacheMut.RLock()
	cache, cached := rssAnnouncementUpdateCache[key]
	rssAnnouncementUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			rssAnnouncementAllColumns,
			rssAnnouncementPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update rss_announcements, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"rss_announcements\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, rssAnnouncementPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(rssAnnouncementType, rssAnnouncementMapping, append(wl, rssAnnouncementPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update rss_announcements row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for rss_announcements")
	}

	if !cached {
		rssAnnouncementUpdateCacheMut.Lock()
		rssAnnouncementUpdateCache[key] = cache
		rssAnnouncementUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (q rssAnnouncementQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q rssAnnouncementQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for rss_announcements")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for rss_announcements")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o RSSAnnouncementSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o RSSAnnouncementSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), rssAnnouncementPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"rss_announcements\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, rssAnnouncementPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in rssAnnouncement slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all rssAnnouncement")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *RSSAnnouncement) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *RSSAnnouncement) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no rss_announcements provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(rssAnnouncementColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	rssAnnouncementUpsertCacheMut.RLock()
	cache, cached := rssAnnouncementUpsertCache[key]
	rssAnnouncementUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			rssAnnouncementAllColumns,
			rssAnnouncementColumnsWithDefault,
			rssAnnouncementColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			rssAnnouncementAllColumns,
			rssAnnouncementPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert rss_announcements, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(rssAnnouncementPrimaryKeyColumns))
			copy(conflict, rssAnnouncementPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"rss_announcements\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(rssAnnouncementType, rssAnnouncementMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(rssAnnouncementType, rssAnnouncementMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert rss_announcements")
	}

	if !cached {
		rssAnnouncementUpsertCacheMut.Lock()
		rssAnnouncementUpsertCache[key] = cache
		rssAnnouncementUpsertCacheMut.Unlock()
	}

	return nil
}

// DeleteG deletes a single RSSAnnouncement record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *RSSAnnouncement) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single RSSAnnouncement record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *RSSAnnouncement) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no RSSAnnouncement provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), rssAnnouncementPrimaryKeyMapping)
	sql := "DELETE FROM \"rss_announcements\" WHERE \"guild_id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from rss_announcements")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for rss_announcements")
	}

	return rowsAff, nil
}

func (q rssAnnouncementQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q rssAnnouncementQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no rssAnnouncementQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from rss_announcements")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for rss_announcements")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o RSSAnnouncementSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o RSSAnnouncementSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), rssAnnouncementPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"rss_announcements\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, rssAnnouncementPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from rssAnnouncement slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for rss_announcements")
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *RSSAnnouncement) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no RSSAnnouncement provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *RSSAnnouncement) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindRSSAnnouncement(ctx, exec, o.GuildID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *RSSAnnouncementSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty RSSAnnouncementSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *RSSAnnouncementSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := RSSAnnouncementSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), rssAnnouncementPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"rss_announcements\".* FROM \"rss_announcements\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, rssAnnouncementPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in RSSAnnouncementSlice")
	}

	*o = slice

	return nil
}

// RSSAnnouncementExistsG checks if the RSSAnnouncement row exists.
func RSSAnnouncementExistsG(ctx context.Context, guildID int64) (bool, error) {
	return RSSAnnouncementExists(ctx, boil.GetContextDB(), guildID)
}

// RSSAnnouncementExists checks if the RSSAnnouncement row exists.
func RSSAnnouncementExists(ctx context.Context, exec boil.ContextExecutor, guildID int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"rss_announcements\" where \"guild_id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, guildID)
	}
	row := exec.QueryRowContext(ctx, sql, guildID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if rss_announcements exists")
	}

	return exists, nil
}
