// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	TicketConfigs      string
	TicketParticipants string
	Tickets            string
}{
	TicketConfigs:      "ticket_configs",
	TicketParticipants: "ticket_participants",
	Tickets:            "tickets",
}
