package reminders

import "github.com/mrbentarikau/pagst/lib/discordgo"

var (
	remindmeLocalizations = map[string]*map[discordgo.Locale]string{
		"AppName": {
			"bg":    "създайте напомняне",
			"cs":    "vytvořit připomínku",
			"da":    "legg til påminnelse",
			"de":    "erinnerung erstellen",
			"el":    "προσθήκη υπενθύμισης",
			"en-GB": "add reminder",
			"en-US": "add reminder",
			"es-ES": "agregar recordatorio",
			"fi":    "lisää muistutus",
			"fr":    "ajouter un rappel",
			"hi":    "अनुस्मारक बनाएँ",
			"hr":    "stvoriti podsjetnik",
			"hu":    "emlékeztető",
			"it":    "aggiungi promemoria",
			"ja":    "リマインダーを作成する",
			"ko":    "알림 생성",
			"lt":    "pridėti priminimą",
			"nl":    "herinnering toevoegen",
			"no":    "opprette påminnelse",
			"pl":    "dodaj przypomnienie",
			"pt-BR": "adicionar lembrete",
			"ro":    "creați memento",
			"ru":    "создать напоминание",
			"sv-SE": "skapa påminnelse",
			"th":    "สร้างการเตือนความจำ",
			"tr":    "hatırlatıcı oluştur",
			"uk":    "додати нагадування",
			"vi":    "tạo lời nhắc",
			"zh-CN": "创建提醒",
			"zh-TW": "創建提醒",
		},
		"ModalTitle": {
			"en-GB": "Remind Me",
			"en-US": "Remind Me",
			"de":    "Erinnere Mich",
			"fi":    "Muistuta Mua",
			"fr":    "Me rappeler",
			"ja":    "備忘",
			"lt":    "Priminti Man",
			"pl":    "Przypomnij Mi",
			"pt-BR": "Lembre-me",
			"sv-SE": "Påminn Mig",
			"ru":    "Напомни Мне",
		},
		"ExtraNotes": {
			"en-GB": "Extra Notes (optional)",
			"en-US": "Extra Notes (optional)",
			"de":    "Zusätzliche Notizen (optional)",
			"fi":    "Lisämerkinnät (valinnainen)",
			"fr":    "Notes supplémentaires (optionnel)",
			"ja":    "メモ　(任意)",
			"lt":    "Papildomos Pastabos (neprivaloma)",
			"pl":    "Notatki (opcjonalne)",
			"pt-BR": "Anotações Extras (opcional)",
			"sv-SE": "Extra Noter (valfritt)",
			"ru":    "Экстра-примечания (опционально)",
		},
		"WhenDate": {
			"en-GB": "When (optional, defaults to 20m)",
			"en-US": "When (optional, defaults to 20m)",
			"de":    "Wann (optional, Standardwert ist 20m)",
			"fi":    "Kun (valinnainen, oletusarvo 20m)",
			"fr":    "Quand? (facultatif, 20m par défaut)",
			"lt":    "Kada (neprivaloma, numatytasis 20m)",
			"ja":    "時間　(任意、デフォルト20分)",
			"pl":    "Kiedy (opcjonalne, domyślnie 20min)",
			"pt-BR": "Quando (opcional, o padrão é 20m)",
			"sv-SE": "När (valfritt, standard 20m)",
			"ru":    "Когда (опционально, по умолчанию 20м)",
		},
	}
)
